apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: DogsAndCats
  annotations:
    version: v0.0.3
    description: "This is my app"
spec:
  components:
    - name: httpserver
      type: capability
      properties:
        contract: wasmcloud:httpserver
        image: wasmcloud.azurecr.io/httpserver:0.17.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
    - name: httpclient
      type: capability
      properties:
        contract: wasmcloud:httpclient
        image: wasmcloud.azurecr.io/httpclient:0.7.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
    - name: dogs-and-cats
      type: actor
      properties:
        image: wasmcloud.azurecr.io/dogs-and-cats:0.2.4 
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: httpserver
            values:
              address: 0.0.0.0:8081
        - type: linkdef
          properties:
            target: httpclient
