wasmcloud:
  # Config options for the wasmCloud Host. See
  # https://wasmcloud.dev/reference/host-runtime/host_configure/ for full details
  config:
    rpcNatsHost: 127.0.0.1
    rpcNatsPort: 4222
    providerNatsHost: 127.0.0.1
    providerNatsPort: 4222
    controlNatsHost: 127.0.0.1
    controlNatsPort: 4222
    # controlTopicPrefix: ""
    # clusterIssuers: ""
    # clusterSeed: ""
    # hostKey: ""
    # latticePrefix: ""
    # rpcJWT: ""
    # rpcTimeout: ""
    # providerRpcJWT: ""
    # providerRpcTimeout: ""
    # ctlJWT: ""
    # providerShutdownDelay: ""
    # hostSeed: ""
    # rpcSeed: ""
    # providerRpcSeed: ""
    # ctlSeed: ""
    jetstreamDomain: "core"
    # logging:
    #   structuredLoggingEnabled: false
    #   logLevel: ""
    # otel:
    #   exporter: ""
    #   endpoint: ""
    # ociAllowedInsecure: ""
    # ociAllowLatest: false
    # Sets the username and password for use with a private registry
    # registry:
    #   url: ""
    #   username: ""
    #   password: ""
    # A map of key value pairs to use as wasmCloud Host labels. These map to environment variable
    # names, so the `.` character is not allowed
    hostLabels:
      kubernetes: "true"
      kind: "true"
  # Enables support for the Kubernetes Applier provider. Essentially, this generates a role and role
  # binding for the pod service account that allows it to get, create, update, delete, and patch
  # service resources if you start the kubernetes applier on one of these hosts. Enabling this
  # option enables service account creation
  enableApplierSupport: true
  # Extra labels to attach to the pod template for each host. Meant for use with things like the
  # Service Applier actor, which requires specific labels in order to route to those pods
  customLabels:
    wasmcloud.dev/route-to: "true"
  image:
    repository: wasmcloud/wasmcloud_host
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.62.1"

nats:
  # Enables the nats container (enabled by default). This can be disabled if you'd like to connect
  # to another in-cluster NATS cluster
  enabled: true
  # The jetstream domain to use for distributed cache data. You'll likely need this if running in
  # production. This is different than the domain used for the host
  jetstreamDomain: "core"
  leafnode:
    # Sets the nats container to operate in leafnode mode
    enabled: true
    # The NATS cluster to connect to. Defaults to NGS
    clusterURL: "tls://connect.ngs.global"
